default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: your_app_development

test:
  <<: *default
  database: your_app_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 15
  timeout: 5000